anmonteiro/lumo

README.md
looking at the boot tasks, the `release` task is necessary to build the binary mentioned in step 3. 
thanks for sharing! looking forward to playing with this :)
=> revise build instructions

src/js/__tests__/util-test.js, src/js/util.js
In Windows, class paths are separated by `;` rather than `:`.  This uses the pre-existing Windows detection flag, `isWindows`, to determine which to use.
=> Add support for Windows-formatted class paths

.gitattributes
This piece of code should hide diffing for that file, more: https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes
=> hide diff results for yarn.lock

build.boot, src/cljs/snapshot/lumo/common.cljs, src/cljs/snapshot/lumo/repl.cljs, test/lumo/repl_tests.cljs, test/lumo/test_util.cljs
Hi Antonio, I added this utility function because `inf-clojure` needs it.
Oddily, the tests are not working on my machine, but the same in the `yarn dev` repl works:
```
cljs.user=> (require '[cljs.test :as test :refer-macros [is]])
nil
cljs.user=> (is (= (lumo/get-arglists "cljs.core/map") '([f] [f coll] [f c1 c2] [f c1 c2 c3] [f c1 c2 c3 & colls])))
true
```
I could not figure out why, but `lumo.repl/resolve-var` calls to `cljs.analyzer` both fail with `#object[Error Error: No protocol method IDeref.-deref defined for type null: ]`. Again, this happenes only in `boot test`, maybe it is running with another version of ClojureScript.
In any case, I'll be waiting for your comments :wink:
=> Add lumo.repl/get-arglists

src/js/cljs.js
=> No longer print returned nil if using -e command line flag

packages/lumo/bin/lumo
Currently installation fails, because npm tries to chmod +x bin/lumo,
and there's nothing there. This adds a placeholder that also gives
the user a helpful message should it happen that their installation
fails halfway.
Fixes #134
=> Add a placeholder bin/lumo script

scripts/aot-bundle-macros.bat, src/cljs/snapshot/lumo/repl.cljs
See #146
Question: should the new `lumo.repl/eval` be exposed anywhere else?
=> Port planck's eval implementation

src/cljs/bundled/lumo/analyzer.cljs
I think ::namespaces here was supposed to refer to :cljs.analyzer/namespaces
=> Namespaced keyword

src/cljs/bundled/lumo/closure.cljs, src/cljs/bundled/lumo/compiler.cljs
Here we go :dagger: 
Some inspiration for the Lumo report:
```clojure
(do (util/debug-prn "\n- Lumo Build Report")
(let [[js-files errors] (split-with #(instance? JavaScriptFile %) sources)]
(print "  [Compiled]")
(if (seq js-files)
(util/debug-prn (->> js-files (map :url) (interleave (repeat "\n    ")) (string/join)))
(util/debug-prn "-"))
(util/debug-prn "  [Failures]" (->> errors
(map :error)
(remove nil?)
(map #(str (.-message %) ": " (.-stack (.-cause %))))
(interleave (repeat "\n    "))
(string/join)))))
```
The patches below do not solve the `core.async` problem, which looks like cannot just find the `ioc_macro.clj` in the file system:
```
[Failures] 
Could not require cljs.core.async.impl.ioc-macros in file cljs/core/async/macros.clj: Error: failed compiling …
```
=> Try to improve the compiler

build.boot, scripts/package.js
...so that the Google Closure Compiler can safely generate source maps.
=> Bundle aot.js.map files

.gitignore
During development, third_party modifications were leaving the git status dirty. Deleting the folder was not possible because `org/clojure/clojurescript` seems checked out. So a rm + checkout was cleaning up things. We can do better and git supports, with some effort, the un-exclusion of only the clojurescript
dir.
=> Ignore the third_party folder, except clojurescript

src/cljs/bundled/lumo/build/api.cljs, src/test/lumo/lumo/build_api_tests.cljs
This change was made necessary by the fact that the bootstrap compiler is
asynchronous by default. Therefore, it does not make sense to call
lumo.build.api/build without a callback.
The patch does not break old code, so it still contains the arity without cb,
but includes a warning if that arity is invoked.
=> Add callback to lumo.build.api/build

CHANGELOG.md, packages/lumo/README.md, src/cljs/bundled/lumo/closure.cljs, src/test/cljs_build/hello/broken_world.cljs, src/test/cljs_build/hello/world.cljs, src/test/lumo/lumo/build_api_tests.cljs
This patch does the actual call to the input compilation callback in case of
success. The returned value is the `:url` of the compiled JavaScript, which
usually is the relative path to it.
Plus minimal documentation.
=> Callback call in case of successful compilation and docs

src/cljs/snapshot/lumo/repl.cljs, src/test/lumo/lumo/repl_tests.cljs
Here it is, spec completions are working fine.
I need some more time if we want to setup a couple of tests, but it looks like it is already working fine. One thing to think about is the position of the completion candidates. I put the before everything at the moment.
Any comment/feedback will be addressed :smile:
=> Add spec completions

CHANGELOG.md, scripts/package.js
The is a strange bug in node 8.5.0 that prevents redirection to work
properly. The bug has solved itself in the new 8.6.0 and therefore lumo can now
follow suit and bump as well.
=> Bump node to 8.6.0 and fixes #283 and #286

src/js/lumo.js
The inferNodeModulesClasspathLibs function becomes recursive so that we can
skip directories that don't contain package.json (like scoped package ones).
My Javascript is super poor and it took actually quite a bit to implement this one,
All the changes in the review on styling will be accepted with no barf :smile:
=> Handle scoped packages when loading Cljs from node dirs

CHANGELOG.md, src/cljs/bundled/lumo/build/api.cljs, src/cljs/bundled/lumo/closure.cljs, src/js/cljs.js
This works and recompiles my changes fast,
example
```
(require 'lumo.build.api)
(lumo.build.api/watch
"samples/hello"
{:optimizations :none
:output-to "samples/out/hello.js"
:output-dir "samples/out"
:cache-analysis true
:source-map true
:verbose true
:watch-fn
(fn []
(println "Success!"))})
```
Few point:
if the directory to watch is not found when passed to `lumo.closure/build` it will not warn that the directory doesn't exist but fail like this
```
Object.fs.openSync (fs.cljs:663:18)
fs.readFileSync (fs.cljs:568:33)
lumo$io$slurp (evalmachine.<anonymous>:11:44)
Function.lumo.analyzer.forms_seq_STAR_.cljs$core$IFn$_invoke$arity$2 (evalmachine.<anonymous>:105:90)
lumo$analyzer$forms_seq_STAR_ (evalmachine.<anonymous>:83:38)
(evalmachine.<anonymous>:263:66) …
```
=> Add watch: lumo.closure/watch and lumo.build.api/watch

.travis.yml, appveyor.yml, circle.yml, src/js/__tests__/__snapshots__/cli-test.js.snap
This is necessary because some error message has changed in the newest Node.
=> [Fix #335] Commit the latest Jest testing snapshots

build.boot
The former is newer and you can set :visual true in profile.boot or even a
custom :theme (pillsbury!).
=> Use notify instead of speak in build.boot

CHANGELOG.md, circle.yml, src/cljs/snapshot/lumo/repl.cljs, src/test/lumo/lumo/repl_tests.cljs
This patch expands on #333 and filters results not only on the suffix but also
on the prefix. This makes sure that we don't return frankstain completions in
case the `line-match-suffix` is empty (effectively not filtering anything).
The problem of the time used to produce the candidates is solved with the use
of `memoize`.
=> Improve robustness of completions 

circle.yml
Installing from the script needs to setup PATH if we cached $HOME/.yarn.
=> Fix Circle CI cached builds when yarn has already been installed

CHANGELOG.md, package.json, packages/lumo/package.json
=> Release 1.8.0

build.boot
Same as for ClojureScript: https://github.com/clojure/tools.reader/tree/tools.reader-1.1.3.1
=> Bump tools.reader to the latest version

build.boot, scripts/package.js
This small patch gives more visibility to the node version. It is now in
build.boot and it can be easily bumped along with the other deps when the time
comes.
=> Include node-version in build.boot

src/cljs/snapshot/lumo/repl.cljs, src/test/lumo/lumo/repl_tests.cljs
I left the forward slash out because it is a more complex case that needs more
time to tackle.
=> [Fix #362] Add plus to completion regex

.travis.yml, CONTRIBUTING.md, appveyor.yml, circle.yml, package.json, packages/lumo/README.md, scripts/test-build, scripts/test-build.bat, src/test/lumo/lumo/build_api_tests.cljs, src/test/lumo/lumo/closure_tests.cljs, src/test/lumo/lumo/js_deps_tests.cljs, src/test/lumo/lumo/repl_tests.cljs, src/test/lumo/lumo/util_tests.cljs
This patch adds some explanation on how to contribute, what the dev workflow is
and how to execute tests.
It is meant to make it a bit easier for new contributors to start hacking.
For instance I added the `t/` alias for `cljs.test` and referred to it in the
CONTRIBUTING.md file so that there is less to type and I have create
`scripts/test-build` (and equivalent Windows script) for running easily against
the built artifact.
=> Add CONTRIBUTING.md and make it easy to run tests

src/cljs/snapshot/lumo/repl.cljs
It looks like the CLJS compiler is now not permitting to recur inside a binding
form. This works around the issue in the only place we do it: print-error.
=> Loop outside binding and fix CLJS master issue

CHANGELOG.md, scripts/aot-bundle-macros.bat, scripts/aot-bundle-macros.sh
By being not required anywhere, the namespace was not compiled by
boot-cljs. Now it is.
=> [Fix #369] Bundle clojure.reflect

build.boot
Thanks David:
https://github.com/cognitect/transit-cljs/commit/a4d7dd3ea550b807597cf1908088d66d34c3d3d7
=> [Fix #359] Use new transit-cljs with MapEntry writing support

packages/lumo/package.json, packages/lumo/scripts/npm_install.js
This is allegedly fix the "Corrupted zip : can't find end of central directory"
that happens often while trying to `npm install -g lumo-cljs`.
As per Slack conversation, we cannot bump to latest `JSZip` because they dropped the sync API.
=> Use yauzl for unzipping npm content on install

.travis.yml
This also makes sure that we use the right version of node in the shells by
setting the right nvm alias.
=> Use Travis cache for yarn and hopefully speed up the build

build.boot, scripts/package.js
A nice use case for the static binary is for building an AWS Custom Runtime,
see also https://github.com/grav/aws-lumo-cljs-runtime
=> Add BUILD_STATIC_BINARY env var for building a static lumo binary
