anmonteiro/lumo

- src/cljs/snapshot/lumo/common.cljs
> Remove unnecessary lazy-load-key

- src/js/__tests__/__snapshots__/cli-test.js.snap
- src/js/cli.js
I did some force-rebaseing that ended with the other pull request was closed. Hope I got it this time.
https://github.com/anmonteiro/lumo/issues/104
https://github.com/anmonteiro/lumo/pull/117
> add node.js compiled version

- .gitignore
- CHANGELOG.md
- build-envs/nixos-16.09_64/Vagrantfile
- scripts/package.js
> Build a fully static binary under Linux

- CHANGELOG.md
- src/cljs/snapshot/lumo/repl.clj
- src/cljs/snapshot/lumo/repl.cljs
- src/js/__tests__/__snapshots__/cli-test.js.snap
- src/js/cli.js
- src/js/cljs.js
- yarn.lock
> `source` REPL special

- package.json
- packages/lumo/README.md
Please merge this pull request to activate your Open Collective https://opencollective.com/lumo
> Activating Open Collective

- package.json
- packages/lumo/bin/lumo
- packages/lumo/bin/lumo.js
- packages/lumo/package.json
- packages/lumo/scripts/npm_install.js
- src/js/cli.js
- src/js/legal.js
> Support git bash on Windows

- build.boot
https://github.com/anmonteiro/lumo/issues/163
> issue #163 fix require bug

- CHANGELOG.md
- src/js/__tests__/__snapshots__/cli-test.js.snap
- src/js/__tests__/cli-test.js
- src/js/__tests__/repl-test.js
- src/js/__tests__/socketRepl-test.js
- src/js/__tests__/util-test.js
- src/js/cli.js
- src/js/util.js
> Support passing Maven coordinates for JAR deps

- packages/lumo/package.json
This solves https://github.com/anmonteiro/lumo/issues/206
tested locally and works.
> add unsafe-perm config in npm script

- src/cljs/snapshot/lumo/repl.cljs
Read more about this PR on  https://github.com/anmonteiro/lumo/issues/222
> Added the lumo.io namespace to completions

- src/cljs/snapshot/lumo/repl.cljs
Feel free to reject this lil' thing.
> Use contains for skip-load? for better clarity

- packages/lumo/README.md
I ran into this issue on a fresh ubuntu zesty, 17.x
> update installation alternative for known issues

- CHANGELOG.md
- src/cljs/bundled/lumo/analyzer.cljs
- src/cljs/bundled/lumo/compiler.cljs
> Load required macro namespaces when reading analysis caches

- src/cljs/snapshot/lumo/repl.cljs
This fixes a WARNING that was showing up while building.
> Move current-alias-map upper in repl.cljs

- circle.yml
Adapting stuff from https://circleci.com/docs/1.0/yarn.
> Attempt another fix for yarn in CircleCi

- build.boot
> Bump node to 9.8.0

- CONTRIBUTING.md
- packages/lumo/README.md
I don't know why, but I mistakenly pasted the raw ones.
> Fix CONTRIBUTING links

- CHANGELOG.md
- build.boot
> Bump node to 9.10.0

- CHANGELOG.md
- src/cljs/snapshot/lumo/repl.cljs
- src/js/cljs.js
instead, show EOF error
fixes #375
> Make `-e` with unfinished form not hang

- CHANGELOG.md
- lib/node.js
- src/js/cljs.js
> ctrl-c during REPL execution exits lumo

- CHANGELOG.md
- src/cljs/snapshot/lumo/repl.cljs
> Correctly set `__dirname` and `__filename` when running script file

- CHANGELOG.md
- src/js/__tests__/util-test.js
- src/js/util.js
> LUMO-320: Allow omitting version in -D

- azure-pipelines.yml
- src/js/__tests__/util-test.js
According to our conversation here is the PR.
You will also have to install the `yarn` extension in your organisation.
This is the build from the branch I'm making this PR: https://strid.visualstudio.com/OSS/_build/results?buildId=128&view=logs
> Use Azure pipelines for Windows CI

- src/cljs/snapshot/lumo/js_deps.cljs
- src/cljs/snapshot/lumo/repl.cljs
- src/js/cljs.js
- src/test/lumo/lumo/js_deps_tests.cljs
> Enable `refer`ing goog namespaces

- src/cljs/snapshot/lumo/js_deps.cljs
- src/cljs/snapshot/lumo/repl.cljs
- src/js/cljs.js
- src/test/lumo/lumo/js_deps_tests.cljs
> Revert "Enable `refer`ing goog namespaces"

- .circleci/config.yml
- .travis.yml
- build.boot
- lib/lumo.js
- package.json
- scripts/embed.js
- scripts/package.js
- src/js/cli.js
- src/js/cljs.js
- src/js/lumo.js
- yarn.lock
> Revert switch to Nexe

- .circleci/config.yml
- .travis.yml
- CHANGELOG.md
- appveyor.yml
- build.boot
- package.json
- scripts/package.js
- src/js/cli.js
- src/js/cljs.js
- yarn.lock
~~This depends on https://github.com/nexe/nexe/pull/606 and causes #453 again, so that will need to be solved before this can be merged.~~
Fixes #462 
There's still the pending issue of a heap space error on Appveyor... But that's orthogonal to this PR.
> Use Nexe again

- CHANGELOG.md
- scripts/package.js
- src/js/repl.js
> ctrl+c should clear the input

- .circleci/config.yml
- .travis.yml
- CHANGELOG.md
- appveyor.yml
- build.boot
- src/js/cljs.js
- vendor/nexe/exe.js
This makes Lumo's startup a little faster.
From https://medium.com/@nodejs/introducing-node-js-12-76c41a1b3f3f:
> Now in Node.js 12 we generate the code cache for built-in libraries in advance at build time, and embed it in the binary, so in the final release, the main thread can use the code cache to start up the initial load of any built-in library written in JavaScript. This gives a ~30% speedup in startup time for the main thread.
> Upgrade to Node.js 12

- scripts/package.js
Quality of life improvement. Useful for debugging.
> Print to stdout the options passed to nexe

- src/cljs/snapshot/lumo/repl.cljs
- src/js/cljs.js
- vendor/nexe/exe.js
> Add ns-aliases and ns-map, refer them at REPL startup
